import {
  Box,
  Button,
  GridItem,
  Image,
  Text,
  Wrap,
  WrapItem,
} from '@chakra-ui/react';

export default function CategoryHomePage() {
  return (
    <Box my="8rem" textAlign="center" h="auto">
      <Text
        my="5rem"
        fontSize="4xl"
        fontFamily="Inter"
        fontWeight="700"
        lineHeight="120%"
        letterSpacing="-1px"
      >
        Les principales catégories de métiers
      </Text>
      <Wrap
        spacing="5rem"
        h="21rem"
        width="85%"
        justify="center"
        height="100%"
        m="auto"
      >
        <WrapItem>
          <GridItem
            height="350px"
            w="340px"
            rounded="20px"
            border="white 9px solid"
            bg="#FFE8E8"
            boxShadow="lg"
            overflow="hidden"
          >
            <Image
              src="Gridlistimage.png"
              zIndex={6}
              position="relative"
              roundedBottom="20px"
              alt="rth"
            />
            <Box
              textAlign="center"
              roundedTop="25px"
              zIndex={7}
              position="relative"
              bg="white"
              p={3}
            >
              <Text
                fontSize="2xl"
                fontFamily="Inter"
                fontWeight="400"
                lineHeight="120%"
                letterSpacing="-1px"
              >
                Scrum Master
              </Text>
              <Button
                mt={4}
                color="white"
                borderRadius="100px"
                size="lg"
                bg="#2945FF"
              >
                Découvrir
              </Button>
            </Box>
          </GridItem>
        </WrapItem>
        <WrapItem>
          <GridItem
            height="350px"
            w="340px"
            rounded="20px"
            border="white 9px solid"
            bg="#FFE8E8"
            boxShadow="lg"
            overflow="hidden"
          >
            <Image
              src="Gridlistimage.png"
              zIndex={6}
              position="relative"
              roundedBottom="20px"
              alt="rth"
            />
            <Box
              textAlign="center"
              roundedTop="25px"
              zIndex={7}
              position="relative"
              bg="white"
              p={3}
            >
              <Text
                fontSize="2xl"
                fontFamily="Inter"
                fontWeight="400"
                lineHeight="120%"
                letterSpacing="-1px"
              >
                Scrum Master
              </Text>
              <Button
                mt={4}
                color="white"
                borderRadius="100px"
                size="lg"
                bg="#2945FF"
              >
                Découvrir
              </Button>
            </Box>
          </GridItem>
        </WrapItem>
        <WrapItem>
          <GridItem
            height="350px"
            w="340px"
            rounded="20px"
            border="white 9px solid"
            bg="#FFE8E8"
            boxShadow="lg"
            overflow="hidden"
          >
            <Image
              src="Gridlistimage.png"
              zIndex={6}
              position="relative"
              roundedBottom="20px"
              alt="rth"
            />
            <Box
              textAlign="center"
              roundedTop="25px"
              zIndex={7}
              position="relative"
              bg="white"
              p={3}
            >
              <Text
                fontSize="2xl"
                fontFamily="Inter"
                fontWeight="400"
                lineHeight="120%"
                letterSpacing="-1px"
              >
                Scrum Master
              </Text>
              <Button
                mt={4}
                color="white"
                borderRadius="100px"
                size="lg"
                bg="#2945FF"
              >
                Découvrir
              </Button>
            </Box>
          </GridItem>
        </WrapItem>
        <WrapItem>
          <GridItem
            height="350px"
            w="340px"
            rounded="20px"
            border="white 9px solid"
            bg="#FFE8E8"
            boxShadow="lg"
            overflow="hidden"
          >
            <Image
              src="Gridlistimage.png"
              zIndex={6}
              position="relative"
              roundedBottom="20px"
              alt="rth"
            />
            <Box
              textAlign="center"
              roundedTop="25px"
              zIndex={7}
              position="relative"
              bg="white"
              p={3}
            >
              <Text
                fontSize="2xl"
                fontFamily="Inter"
                fontWeight="400"
                lineHeight="120%"
                letterSpacing="-1px"
              >
                Scrum Master
              </Text>
              <Button
                mt={4}
                color="white"
                borderRadius="100px"
                size="lg"
                bg="#2945FF"
              >
                Découvrir
              </Button>
            </Box>
          </GridItem>
        </WrapItem>
        <WrapItem>
          <GridItem
            height="350px"
            w="340px"
            rounded="20px"
            border="white 9px solid"
            bg="#FFE8E8"
            boxShadow="lg"
            overflow="hidden"
          >
            <Image
              src="Gridlistimage.png"
              zIndex={6}
              position="relative"
              roundedBottom="20px"
              alt="rth"
            />
            <Box
              textAlign="center"
              roundedTop="25px"
              zIndex={7}
              position="relative"
              bg="white"
              p={3}
            >
              <Text
                fontSize="2xl"
                fontFamily="Inter"
                fontWeight="400"
                lineHeight="120%"
                letterSpacing="-1px"
              >
                Scrum Master
              </Text>
              <Button
                mt={4}
                color="white"
                borderRadius="100px"
                size="lg"
                bg="#2945FF"
              >
                Découvrir
              </Button>
            </Box>
          </GridItem>
        </WrapItem>
      </Wrap>
    </Box>
  );
}
