name: deploy nexturl to vercel

on:
  push:
    branches: [ fix/ci-cd ]
    paths:
      - 'app/**'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write app/*.{js,md}
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Testing
          uses: actions/checkout@v2
          with:
            script: |
              npm ci
              npm run test
  deploy:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-project-id: ${{ secrets.PREPROD_VERCEL_PROJECTID}}
          vercel-org-id: ${{ secrets.PREPROD_VERCEL_ORGID}}